import React from "react";
import AccountForm from "./auth-form";
export const metadata = {
  title: "panjab university | login ",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="  px-6  bg-neutral-300  h-screen w-full flex justify-center items-center">
      <AccountForm />
    </div>
  );
};

export default page;
