import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "panjab university",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html style={inter.style} lang="en">
      <body>
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
